import { adminOrders } from '@/lib/admin/orders-data'
import { adminCustomers } from '@/lib/admin/customers-data'

// Mock product data for Gelos
export const products = [
  {
    id: "1",
    name: "Watermelon Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.9,
    reviews: 286,
    image: "/gelos/watermelon-toothpaste.png",
    description: "Fluoride+ watermelon toothpaste for a fresh, fruity clean",
    stock: 45,
  },
  {
    id: "9",
    name: "Grape Mint Fruit Energy",
    category: "Wellness",
    price: 80.0,
    rating: 4.9,
    reviews: 312,
    image: "/gelos/grape-mint-fruit-energy.png",
    description: "Portable fruit energy case with grape mint flavor",
    stock: 52,
  },
  {
    id: "2",
    name: "Stainless Steel Tongue Scraper",
    category: "Tongue Scraper",
    price: 9.99,
    rating: 4.9,
    reviews: 89,
    image: "/gelos/IMG_8035.JPG",
    description: "Professional-grade tongue scraper for optimal oral hygiene",
    stock: 72,
  },
  {
    id: "23",
    name: "Copper Tongue Scraper",
    category: "Tongue Scraper",
    price: 12.99,
    rating: 4.8,
    reviews: 64,
    image: "/gelos/IMG_8030.JPG",
    description: "Premium copper tongue scraper for a refined daily fresh-breath ritual",
    stock: 58,
  },
  {
    id: "3",
    name: "V34 Shade Correction Kit",
    category: "Whitening",
    price: 34.99,
    rating: 4.7,
    reviews: 203,
    image: "/gelos/GELOS1967.jpg",
    description: "Complete V34 shade correction system for professional results",
    stock: 28,
  },
  {
    id: "4",
    name: "Activated Charcoal Powder",
    category: "Whitening",
    price: 14.99,
    rating: 4.6,
    reviews: 156,
    image: "/gelos/GELOS2052.jpg",
    description: "Pure activated charcoal for natural teeth whitening",
    stock: 92,
  },
  {
    id: "5",
    name: "Aromatherapy Nasal Inhaler",
    category: "Wellness",
    price: 8.99,
    rating: 4.5,
    reviews: 67,
    image: "/gelos/mango-inhaler.png",
    description: "Refreshing nasal inhaler with therapeutic essential oils",
    stock: 58,
  },
  {
    id: "6",
    name: "Candy Cane  Toothpaste",
    category: "Accessories",
    price: 6.99,
    rating: 4.3,
    reviews: 45,
    image: "/gelos/GELOS2141.jpg",
    description: "Metallic tooth tattoos for fun dental decoration",
    stock: 115,
  },
  {
    id: "7",
    name: "Premium Whitening Strips (30 pairs)",
    category: "Whitening",
    price: 24.99,
    rating: 4.8,
    reviews: 178,
    image: "/gelos/strips.png",
    description: "Professional whitening strips for 14-day results",
    stock: 36,
  },
  {
    id: "8",
    name: "Bamboo Toothbrush Set (3-pack)",
    category: "Toothbrushes",
    price: 11.99,
    rating: 4.7,
    reviews: 98,
    image: "/gelos/bb.brushbl.png",
    description: "Eco-friendly bamboo toothbrushes with soft bristles",
    stock: 64,
  },
  {
    id: "24",
    name: "3D Sonicwave G1 Electric Toothbrush",
    category: "Toothbrushes",
    price: 49.99,
    rating: 4.8,
    reviews: 87,
    image: "/gelos/3d-sonicwave-g1-electric-toothbrush.png",
    description: "Rechargeable sonic electric toothbrush for a deeper daily clean",
    stock: 32,
  },
  {
    id: "10",
    name: "LED Whitening Device",
    category: "Whitening",
    price: 129.99,
    rating: 4.9,
    reviews: 245,
    image: "/gelos/led-whitening-device.png",
    description: "Professional LED teeth whitening device with purple light tray",
    stock: 34,
  },
  {
    id: "11",
    name: "Energy Drink Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.8,
    reviews: 198,
    image: "/gelos/energy-drink-toothpaste.png",
    description: "Fluoride+ energy drink toothpaste for a bold, refreshing clean",
    stock: 61,
  },
  {
    id: "12",
    name: "Watermelon Foaming Mouthwash",
    category: "Mouthwash",
    price: 88.0,
    rating: 4.9,
    reviews: 221,
    image: "/gelos/mouthwash-watermelon.png",
    description: "Alcohol-free foaming mouthwash — fresh watermelon flavour, 60+ uses",
    stock: 48,
  },
  {
    id: "13",
    name: "Coconut Whip Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.9,
    reviews: 142,
    image: "/gelos/coconut-whip-toothpaste.png",
    description: "Fluoride+ coconut whip toothpaste — creamy tropical freshness",
    stock: 55,
  },
  {
    id: "14",
    name: "Banana Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.8,
    reviews: 128,
    image: "/gelos/bananaa.png",
    description: "Fluoride+ banana toothpaste for a smooth, fruity clean",
    stock: 48,
  },
  {
    id: "15",
    name: "Strawberry Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.9,
    reviews: 167,
    image: "/gelos/strawberry-toothpaste.png",
    description: "Fluoride+ strawberry toothpaste — sweet and refreshing",
    stock: 62,
  },
  {
    id: "16",
    name: "Passion Fruit Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.8,
    reviews: 119,
    image: "/gelos/passion-fruit-toothpaste.png",
    description: "Fluoride+ passion fruit toothpaste with a bold tropical twist",
    stock: 41,
  },
  {
    id: "17",
    name: "Grape Bubblegum Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.9,
    reviews: 154,
    image: "/gelos/grape-bubblegum-toothpaste.png",
    description: "Fluoride+ grape bubblegum toothpaste — fun and fresh",
    stock: 57,
  },
  {
    id: "18",
    name: "Vanilla Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.7,
    reviews: 103,
    image: "/gelos/vanilla-toothpaste.png",
    description: "Fluoride+ vanilla toothpaste — smooth dessert-inspired clean",
    stock: 39,
  },
  {
    id: "19",
    name: "Red Velvet Toothpaste",
    category: "Toothpaste",
    price: 80.0,
    rating: 4.8,
    reviews: 136,
    image: "/gelos/red-velvet-toothpaste.png",
    description: "Fluoride+ red velvet toothpaste — rich and indulgent",
    stock: 44,
  },
  {
    id: "20",
    name: "Strawberry Foaming Mouthwash",
    category: "Mouthwash",
    price: 88.0,
    rating: 4.9,
    reviews: 187,
    image: "/gelos/mouthwash-strawberry.png",
    description: "Alcohol-free foaming mouthwash — sweet strawberry freshness, 50+ uses",
    stock: 52,
  },
  {
    id: "21",
    name: "Blue Raspberry Foaming Mouthwash",
    category: "Mouthwash",
    price: 88.0,
    rating: 4.8,
    reviews: 164,
    image: "/gelos/mouthwash-blue-raspberry.png",
    description: "Alcohol-free foaming mouthwash — bold blue raspberry flavour",
    stock: 46,
  },
  {
    id: "22",
    name: "Grape Bubblegum Foaming Mouthwash",
    category: "Mouthwash",
    price: 88.0,
    rating: 4.9,
    reviews: 173,
    image: "/gelos/mouthwash-grape-bubblegum.png",
    description: "Alcohol-free foaming mouthwash — grape bubblegum burst, 50+ uses",
    stock: 50,
  },
];

/** Store orders for admin & dashboard (see lib/admin/orders-data.ts) */
export const orders = adminOrders

/** Store customers for admin (see lib/admin/customers-data.ts) */
export const customers = adminCustomers

export const analyticsData = [
  { month: "Jan", sales: 4000, orders: 24, revenue: 12000 },
  { month: "Feb", sales: 3000, orders: 18, revenue: 9500 },
  { month: "Mar", sales: 2000, orders: 14, revenue: 6800 },
  { month: "Apr", sales: 2780, orders: 22, revenue: 8500 },
  { month: "May", sales: 1890, orders: 15, revenue: 5800 },
  { month: "Jun", sales: 2390, orders: 28, revenue: 7200 },
];
